// Definition of Enum-Values that should be used as strings as well
ESTRING (MQTTaddress)
ESTRING (MQTTclientID)
ESTRING (MQTTtopic)
ESTRING (WS_Reihung_Nr_1)
ESTRING (WS_Reihung_Nr_2)
ESTRING (WS_Reihung_Nr_3)
ESTRING (ADC_BAND_LEVEL_1)  //ADC wert wen kein Ws aufband
ESTRING (ADC_WS_HOCH_LEVEL_1) //ADC wert wen ein Hoches WS ohne Bohrung gemessen wird
ESTRING (ADC_BAND_LEVEL_2)
ESTRING (ADC_WS_HOCH_LEVEL_2)
ESTRING (T_RUTSCHE_VOLL) //####mit konstruktor
ESTRING (TOLERANZ_MESSZEITEN) //####mit konstruktor
ESTRING (FBM1_WS_EINLEGEN_ZEIT) //####mit konstruktor
ESTRING (FBM1_LAENGSTE_ZEIT_BIS_HS) //zeit zwischen lS_A_AUS->HS
ESTRING (FBM1_KUERZTE_ZEIT_BIS_HS)
ESTRING (FBM1_MESSZEIT)
ESTRING (FBM1_LAENGSTE_ZEIT_BIS_SEP)
ESTRING (FBM1_KUERZESTE_ZEIT_BIS_SEP)
ESTRING (FBM1_ZEIT_WS_PASSIERT_WEICHE)
ESTRING (FBM1_LAENGSTE_ZEIT_BIS_LS_ENDE)
ESTRING (FBM1_KUERZESTE_ZEIT_BIS_LS_ENDE)
ESTRING (FBM1_LAENGSTE_ZEIT_BIS_LS_RUT)
ESTRING (FBM1_LAENGSTE_ZEIT_WS_UEBERGEBEN)
ESTRING (FBM1_AUSWERFER_TRUE)
ESTRING (FBM2_LAENGSTE_ZEIT_BIS_LS_ANFANG)
ESTRING (FBM2_LAENGSTE_ZEIT_BIS_HS)
ESTRING (FBM2_KUERZTE_ZEIT_BIS_HS)
ESTRING (FBM2_MESSZEIT)
ESTRING (FBM2_LAENGSTE_ZEIT_BIS_SEP)
ESTRING (FBM2_KUERZESTE_ZEIT_BIS_SEP)
ESTRING (FBM2_ZEIT_WS_PASSIERT_WEICHE)
ESTRING (FBM2_LAENGSTE_ZEIT_BIS_LS_ENDE)
ESTRING (FBM2_KUERZESTE_ZEIT_BIS_LS_ENDE)
ESTRING (FBM2_LAENGSTE_ZEIT_BIS_LS_RUT)
ESTRING (FBM2_AUSWERFER_TRUE)
ESTRING (MAX_ENUM) //Immer als Letzter Enum!!!
